### ISSUE TITLE
Error retrieve access token through refresh token: `value cannot be null`

### ISSUE THREAD

**Issue by aboutZZ** [dromara/dante-cloud#6] opened 2023-01-20 01:59 UTC
`OAuth2SocialCredentialsAuthenticationProvider` provide the phone login, but when I try to retrieve access token by refresh token, error occured.
```
java.lang.IllegalArgumentException: value cannot be null
	at org.springframework.util.Assert.notNull(Assert.java:204)
	at org.springframework.security.oauth2.server.authorization.token.OAuth2TokenContext$AbstractBuilder.put(OAuth2TokenContext.java:229)
	at org.springframework.security.oauth2.server.authorization.token.OAuth2TokenContext$AbstractBuilder.principal(OAuth2TokenContext.java:156)
	at org.springframework.security.oauth2.server.authorization.authentication.OAuth2RefreshTokenAuthenticationProvider.authenticate(OAuth2RefreshTokenAuthenticationProvider.java:149)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
	at org.springframework.security.authentication.ObservationAuthenticationManager.lambda$authenticate$1(ObservationAuthenticationManager.java:53)
..... more frames ....
```

`OAuth2RefreshTokenAuthenticationProvider` put the pricipal from `OAuth2Authorization` attribute with the key `java.security.Principal`, which is null. The `OAuth2SocialCredentialsAuthenticationProvider` is not set and save this attribute when `authenticate`
```java
OAuth2Authorization.Builder authorizationBuilder = OAuth2Authorization.withRegisteredClient(registeredClient)
            .principalName(usernamePasswordAuthentication.getName())
            .authorizationGrantType(HerodotusGrantType.SOCIAL)
            // java.security.Principal attribute must be set.
            .attribute(Principal.class.getName(), somePrincipal)
            .authorizedScopes(authorizedScopes);

```

**Comment by herodotus-ecosystem** [comment] 2023-01-20 03:01
### 1. To describe a problem, you need to provide a detailed explanation rather than just say the result. Otherwise, we can only rely on guess to infer the cause of the problem. Including but not limited to：

- What operations and specific steps did you do before the error occurred, including where to modify, whether to compile the code, etc
- What interface is accessed?
- What parameters are passed?
- What error did the back-end console report?
- What error did the front-end console report?
- What version was used? What version have you upgraded to now?
- Start error or run error? Which interface is called when running an error?

### 2. Judging from your description, it is likely that the usage is incorrect or the code version is incorrect

- The code OAuth2SocialCredentialsAuthenticationProvider will be called only when access token is obtained using social mode
- When you use the refresh token to obtain the access token again, only the code OAuth2RefreshTokenAuthenticationProvider will be called

I guess it is very likely that your code version is used incorrectly, or that you call the requested method incorrectly

![image](https://user-images.githubusercontent.com/11025512/213608714-bcf36df2-e725-457c-9dce-cb69f1700f7a.png)

### 3. Github's domestic visit is relatively slow. If there is a problem, it is recommended to use gitee to get the author's reply faster

**Comment by aboutZZ** [comment] 2023-01-20 03:28
Thanks for your reply, I'm using Spring boot 3.0.1, does 3.0.0 branch fix this issue?

**Comment by herodotus-ecosystem** [comment] 2023-01-20 07:31
> Thanks for your reply, I'm using Spring boot 3.0.1, does 3.0.0 branch fix this issue?

Please wait for the Dante Cloud v3.0.2.0 to be released, which will be released today。

**Closed as completed** 2023-01-20 10:58 UTC
